name: "There's a typo"
description: "I found a typo in the docs."
title: "[typo] Feedback on <name of page>"
labels: ["feedback", "bug"]
body:
  - type: textarea
    id: page-url
    attributes:
      label: Page
      description: Enter the URL of the page you're reviewing.
    validations:
      required: true
  - type: textarea
    id: what-do-you-see
    attributes:
      label: What do you see?
      description: Describe what you currently see on the page.
    validations:
      required: true
  - type: textarea
    id: what-were-you-expecting-to-see
    attributes:
      label: What were you expecting to see?
      description: Describe what expected to see on the page.
    validations:
      required: true